openapi: 3.1.0
info:
  title: PR Reviewer Assignment Service (Test Task, Fall 2025)
  description: ''
  version: 1.0.0
tags:
  - name: Teams
  - name: Users
  - name: PullRequests
paths:
  /team/add:
    post:
      summary: Создать команду с участниками (создаёт/обновляет пользователей)
      deprecated: false
      description: ''
      tags:
        - Teams
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Team'
            example:
              team_name: payments
              members:
                - user_id: u1
                  username: Alice
                  is_active: true
                - user_id: u2
                  username: Bob
                  is_active: true
        required: true
      responses:
        '201':
          description: Команда создана
          content:
            application/json:
              schema:
                type: object
                properties:
                  team:
                    $ref: '#/components/schemas/Team'
                x-apidog-orders:
                  - team
                x-apidog-ignore-properties: []
              example:
                team:
                  team_name: backend
                  members:
                    - user_id: u1
                      username: Alice
                      is_active: true
                    - user_id: u2
                      username: Bob
                      is_active: true
          headers: {}
          x-apidog-name: Created
        '400':
          description: Команда уже существует
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                error:
                  code: TEAM_EXISTS
                  message: team_name already exists
          headers: {}
          x-apidog-name: Bad Request
      security: []
      x-apidog-folder: Teams
      x-apidog-status: released
      x-run-in-apidog: https://app.apidog.com/web/project/1128883/apis/api-24340678-run
  /team/get:
    get:
      summary: Получить команду с участниками
      deprecated: false
      description: ''
      tags:
        - Teams
      parameters:
        - name: team_name
          in: query
          description: Уникальное имя команды
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Объект команды
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Team'
              example:
                team_name: backend
                members:
                  - user_id: u1
                    username: Alice
                    is_active: true
                  - user_id: u2
                    username: Bob
                    is_active: true
          headers: {}
          x-apidog-name: OK
        '404':
          description: Команда не найдена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          headers: {}
          x-apidog-name: Not Found
      security: []
      x-apidog-folder: Teams
      x-apidog-status: released
      x-run-in-apidog: https://app.apidog.com/web/project/1128883/apis/api-24340679-run
  /users/setIsActive:
    post:
      summary: Установить флаг активности пользователя
      deprecated: false
      description: ''
      tags:
        - Users
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - user_id
                - is_active
              properties:
                user_id:
                  type: string
                is_active:
                  type: boolean
              x-apidog-orders:
                - user_id
                - is_active
              x-apidog-ignore-properties: []
            example:
              user_id: u2
              is_active: false
        required: true
      responses:
        '200':
          description: Обновлённый пользователь
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    $ref: '#/components/schemas/User'
                x-apidog-orders:
                  - user
                x-apidog-ignore-properties: []
              example:
                user:
                  user_id: u2
                  username: Bob
                  team_name: backend
                  is_active: false
          headers: {}
          x-apidog-name: OK
        '404':
          description: Пользователь не найден
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          headers: {}
          x-apidog-name: Not Found
      security: []
      x-apidog-folder: Users
      x-apidog-status: released
      x-run-in-apidog: https://app.apidog.com/web/project/1128883/apis/api-24340680-run
  /users/getReview:
    get:
      summary: Получить PR'ы, где пользователь назначен ревьювером
      deprecated: false
      description: ''
      tags:
        - Users
      parameters:
        - name: user_id
          in: query
          description: Идентификатор пользователя
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Список PR'ов пользователя
          content:
            application/json:
              schema:
                type: object
                required:
                  - user_id
                  - pull_requests
                properties:
                  user_id:
                    type: string
                  pull_requests:
                    type: array
                    items:
                      $ref: '#/components/schemas/PullRequestShort'
                x-apidog-orders:
                  - user_id
                  - pull_requests
                x-apidog-ignore-properties: []
              example:
                user_id: u2
                pull_requests:
                  - pull_request_id: pr-1001
                    pull_request_name: Add search
                    author_id: u1
                    status: OPEN
          headers: {}
          x-apidog-name: OK
      security: []
      x-apidog-folder: Users
      x-apidog-status: released
      x-run-in-apidog: https://app.apidog.com/web/project/1128883/apis/api-24340681-run
  /pullRequest/statistics:
    get:
      summary: Статистика PR
      deprecated: false
      description: Получение всех PR с количеством назначеных пользователей
      tags:
        - PullRequests
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  stat:
                    type: array
                    items:
                      type: object
                      properties:
                        pull_request_id:
                          type: string
                        quantity_reviewers:
                          type: integer
                      x-apidog-orders:
                        - pull_request_id
                        - quantity_reviewers
                      x-apidog-ignore-properties: []
                x-apidog-orders:
                  - 01KA71126A5HFA8TWN2023KHZ0
                required:
                  - stat
                x-apidog-refs:
                  01KA71126A5HFA8TWN2023KHZ0:
                    $ref: '#/components/schemas/PullRequestStat'
                x-apidog-ignore-properties:
                  - stat
          headers: {}
          x-apidog-name: Success
      security: []
      x-apidog-folder: PullRequests
      x-apidog-status: released
      x-run-in-apidog: https://app.apidog.com/web/project/1128883/apis/api-24340686-run
  /pullRequest/create:
    post:
      summary: Создать PR и автоматически назначить до 2 ревьюверов из команды автора
      deprecated: false
      description: ''
      tags:
        - PullRequests
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - pull_request_id
                - pull_request_name
                - author_id
              properties:
                pull_request_id:
                  type: string
                pull_request_name:
                  type: string
                author_id:
                  type: string
              x-apidog-orders:
                - pull_request_id
                - pull_request_name
                - author_id
              x-apidog-ignore-properties: []
            example:
              pull_request_id: pr-1001
              pull_request_name: Add search
              author_id: u1
        required: true
      responses:
        '201':
          description: PR создан
          content:
            application/json:
              schema:
                type: object
                properties:
                  pr:
                    $ref: '#/components/schemas/PullRequest'
                x-apidog-orders:
                  - pr
                x-apidog-ignore-properties: []
              example:
                pr:
                  pull_request_id: pr-1001
                  pull_request_name: Add search
                  author_id: u1
                  status: OPEN
                  assigned_reviewers:
                    - u2
                    - u3
          headers: {}
          x-apidog-name: Created
        '404':
          description: Автор/команда не найдены
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          headers: {}
          x-apidog-name: Not Found
        '409':
          description: PR уже существует
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                error:
                  code: PR_EXISTS
                  message: PR id already exists
          headers: {}
          x-apidog-name: Conflict
      security: []
      x-apidog-folder: PullRequests
      x-apidog-status: released
      x-run-in-apidog: https://app.apidog.com/web/project/1128883/apis/api-24340682-run
  /pullRequest/merge:
    post:
      summary: Пометить PR как MERGED (идемпотентная операция)
      deprecated: false
      description: ''
      tags:
        - PullRequests
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - pull_request_id
              properties:
                pull_request_id:
                  type: string
              x-apidog-orders:
                - pull_request_id
              x-apidog-ignore-properties: []
            example:
              pull_request_id: pr-1001
        required: true
      responses:
        '200':
          description: PR в состоянии MERGED
          content:
            application/json:
              schema:
                type: object
                properties:
                  pr:
                    $ref: '#/components/schemas/PullRequest'
                x-apidog-orders:
                  - pr
                x-apidog-ignore-properties: []
              example:
                pr:
                  pull_request_id: pr-1001
                  pull_request_name: Add search
                  author_id: u1
                  status: MERGED
                  assigned_reviewers:
                    - u2
                    - u3
                  mergedAt: '2025-10-24T12:34:56.000Z'
          headers: {}
          x-apidog-name: OK
        '404':
          description: PR не найден
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          headers: {}
          x-apidog-name: Not Found
      security: []
      x-apidog-folder: PullRequests
      x-apidog-status: released
      x-run-in-apidog: https://app.apidog.com/web/project/1128883/apis/api-24340683-run
  /pullRequest/reassign:
    post:
      summary: Переназначить конкретного ревьювера на другого из его команды
      deprecated: false
      description: ''
      tags:
        - PullRequests
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - pull_request_id
                - old_user_id
              properties:
                pull_request_id:
                  type: string
                old_user_id:
                  type: string
              x-apidog-orders:
                - pull_request_id
                - old_user_id
              x-apidog-ignore-properties: []
            example:
              pull_request_id: pr-1001
              old_reviewer_id: u2
        required: true
      responses:
        '200':
          description: Переназначение выполнено
          content:
            application/json:
              schema:
                type: object
                required:
                  - pr
                  - replaced_by
                properties:
                  pr:
                    $ref: '#/components/schemas/PullRequest'
                  replaced_by:
                    type: string
                    description: user_id нового ревьювера
                x-apidog-orders:
                  - pr
                  - replaced_by
                x-apidog-ignore-properties: []
              example:
                pr:
                  pull_request_id: pr-1001
                  pull_request_name: Add search
                  author_id: u1
                  status: OPEN
                  assigned_reviewers:
                    - u3
                    - u5
                replaced_by: u5
          headers: {}
          x-apidog-name: OK
        '404':
          description: PR или пользователь не найден
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          headers: {}
          x-apidog-name: Not Found
        '409':
          description: Нарушение доменных правил переназначения
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                '2':
                  summary: Нельзя менять после MERGED
                  value:
                    error:
                      code: PR_MERGED
                      message: cannot reassign on merged PR
                '3':
                  summary: Пользователь не был назначен ревьювером
                  value:
                    error:
                      code: NOT_ASSIGNED
                      message: reviewer is not assigned to this PR
                '4':
                  summary: Нет доступных кандидатов
                  value:
                    error:
                      code: NO_CANDIDATE
                      message: no active replacement candidate in team
          headers: {}
          x-apidog-name: Conflict
      security: []
      x-apidog-folder: PullRequests
      x-apidog-status: released
      x-run-in-apidog: https://app.apidog.com/web/project/1128883/apis/api-24340684-run
webhooks: {}
components:
  schemas:
    PullRequestStat:
      type: object
      properties:
        stat:
          type: array
          items:
            type: object
            properties:
              pull_request_id:
                type: string
              quantity_reviewers:
                type: integer
            x-apidog-orders:
              - pull_request_id
              - quantity_reviewers
            x-apidog-ignore-properties: []
      required:
        - stat
      x-apidog-orders:
        - stat
      x-apidog-ignore-properties: []
      x-apidog-folder: ''
    ErrorResponse:
      type: object
      required:
        - error
      properties:
        error:
          type: object
          required:
            - code
            - message
          properties:
            code:
              type: string
              enum:
                - TEAM_EXISTS
                - PR_EXISTS
                - PR_MERGED
                - NOT_ASSIGNED
                - NO_CANDIDATE
                - NOT_FOUND
            message:
              type: string
          x-apidog-orders:
            - code
            - message
          x-apidog-ignore-properties: []
      x-apidog-orders:
        - error
      examples:
        - error:
            code: NOT_FOUND
            message: resource not found
      x-apidog-ignore-properties: []
      x-apidog-folder: ''
    TeamMember:
      type: object
      required:
        - user_id
        - username
        - is_active
      properties:
        user_id:
          type: string
        username:
          type: string
        is_active:
          type: boolean
      x-apidog-orders:
        - user_id
        - username
        - is_active
      x-apidog-ignore-properties: []
      x-apidog-folder: ''
    Team:
      type: object
      required:
        - team_name
        - members
      properties:
        team_name:
          type: string
        members:
          type: array
          items:
            $ref: '#/components/schemas/TeamMember'
      x-apidog-orders:
        - team_name
        - members
      x-apidog-ignore-properties: []
      x-apidog-folder: ''
    User:
      type: object
      required:
        - user_id
        - username
        - team_name
        - is_active
      properties:
        user_id:
          type: string
        username:
          type: string
        team_name:
          type: string
        is_active:
          type: boolean
      x-apidog-orders:
        - user_id
        - username
        - team_name
        - is_active
      x-apidog-ignore-properties: []
      x-apidog-folder: ''
    PullRequest:
      type: object
      required:
        - pull_request_id
        - pull_request_name
        - author_id
        - status
        - assigned_reviewers
      properties:
        pull_request_id:
          type: string
        pull_request_name:
          type: string
        author_id:
          type: string
        status:
          type: string
          enum:
            - OPEN
            - MERGED
        assigned_reviewers:
          type: array
          items:
            type: string
          description: user_id назначенных ревьюверов (0..2)
        createdAt:
          type:
            - string
            - 'null'
          format: date-time
        mergedAt:
          type:
            - string
            - 'null'
          format: date-time
      x-apidog-orders:
        - pull_request_id
        - pull_request_name
        - author_id
        - status
        - assigned_reviewers
        - createdAt
        - mergedAt
      x-apidog-ignore-properties: []
      x-apidog-folder: ''
    PullRequestShort:
      type: object
      required:
        - pull_request_id
        - pull_request_name
        - author_id
        - status
      properties:
        pull_request_id:
          type: string
        pull_request_name:
          type: string
        author_id:
          type: string
        status:
          type: string
          enum:
            - OPEN
            - MERGED
      x-apidog-orders:
        - pull_request_id
        - pull_request_name
        - author_id
        - status
      x-apidog-ignore-properties: []
      x-apidog-folder: ''
  securitySchemes: {}
servers: []
security: []
